#!/bin/sh

if [ $RUN_COMPOSER = "yes" ]; then
if [ -e /usr/share/nginx/html/composer.lock ]; then
    #if composer.lock exists, just update the project.
    (cd /usr/share/nginx/html && composer update)
elif [ -e /usr/share/nginx/html/composer.json ]; then
    #if composer.json exists, install the project.
    (cd /usr/share/nginx/html && composer install)
else
    #if neither exists, create the project.
    (cd /usr/share/nginx/ && composer create-project --prefer-dist $COMPOSER_PACKAGE html)
fi

if [ -e /usr/share/nginx/laravel.env ]; then
chmod -R 777 /usr/share/nginx/html/storage
chmod -R 777 /usr/share/nginx/html/bootstrap
rm -rf /usr/share/nginx/html/.env
cp /usr/share/nginx/laravel.env /usr/share/nginx/html/.env
fi

fi

set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

exec "$@"
